seed: 512
data:
    data_dir: './data' 
    dataset_name: ['dataset_07-10-2023_23-01-21','dataset_07-10-2023_23-02-13']
    state_dim: 5
    image_size: [256,256]  
  
train:
    device: 'cuda'
    epochs: -1
    lr: 0.0001
    batch_size: 5
eval:
    model_path: /home/raghava/projects/vine-proprio/.log/log_07-05-2023_09-42-58/chpt_final.pth
    compute_type: 'cuda:0'
